[package]
name = "gramide_typescript"
version = "0.3.2"
edition = "2026"

[dependencies]
gramide = { git = "https://github.com/O6lvl4/gramide", tag = "v0.2.1" }
gramide_javascript = { git = "https://github.com/O6lvl4/gramide-javascript", tag = "v0.3.2" }
